- name: Deploy the hello microshift demo app
  hosts: microshift
  become: true
  tasks:
    - name: Ensure manifest directory exists
      ansible.builtin.file:
        path: /etc/microshift/manifests
        state: directory
        mode: "0755"

    - name: Pull kustomize manifest
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/redhat-et/microshift-demos/main/apps/hello-microshift/{{ item }}.yaml"
        dest: "/etc/microshift/manifests/{{ item }}.yaml"
        mode: "0644"
      loop:
        - kustomization
        - deployment
        - namespace
        - route
        - service
      notify: Restart microshift

  handlers:
    - name: Restart microshift
      ansible.builtin.systemd:
        service: microshift
        state: restarted

# vim: ft=yaml.ansible
