---
name: Release the ansible collection
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  release:
    uses: ansible/devtools/.github/workflows/release_collection.yml@main
    with:
      environment: release
      galaxy_publish: false
    secrets:
      ah_token: ${{ secrets.AH_TOKEN }}
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
